name: CI/CD Pipeline

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  OIDC_ROLE_NAME: find-optimal-time-slot-github-oidc-role
  AWS_REGION: eu-west-1
  PYTHON_VERSION: 3.13
  TERRAFORM_VERSION: 1.13.5

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest tests/unit -vv

  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build Lambda package
        run: ./optimal_time_slot_lambda/build.sh

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [unit_tests, build_and_deploy]
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Get API URL from Terraform
        working-directory: terraform
        run: |
          echo "::stop-commands::noecho"
          API_URL=$(terraform output -raw api_url)
          echo "::noecho::"
          echo "API_URL='$API_URL'"
          echo "API_URL=$API_URL" >> $GITHUB_ENV

      - name: Run integration tests
        run: pytest tests/integration -vv
        env:
          API_URL: ${{ env.API_URL }}
